version: '3.8'

services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development

  backend:
    image: python:3.9
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    command: uvicorn app.main:app --reload --host 0.0.0.0
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: